### ISSUE TITLE
compiler broken

### ISSUE THREAD

**Issue by jleppert** [adamhaile/surplus#39]
````
> require('surplus');
{ insert: [Function: insert$$1],
  S:
   { [Function: S]
     root: [Function: root],
     on: [Function: on],
     data: [Function: data],
     value: [Function: value],
     freeze: [Function: freeze],
     sample: [Function: sample],
     cleanup: [Function: cleanup] },
  createElement: [Function: createElement],
  createComment: [Function: createComment],
  createTextNode: [Function: createTextNode],
  appendChild: [Function: appendChild] }
> require('surplus/compiler');
Error: Cannot find module 'surplus/compiler'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
> require('surplus/compiler');
Error: Cannot find module 'surplus/compiler'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
>
```

**Comment by adamhaile** [comment]
The docs are for version 0.5, which is in beta.  If you run `npm install surplus@beta` you'll get it.  Sorry for the confusion -- I'm going to add a note saying such to the readme.
